window.INDUSCOUT_DATA = {
  categoryTaxonomy: [
    {
      name: "Sensors",
      slug: "sensors",
      summary: "Proximity, photoelectric, pressure, level, and machine detection sensors.",
      focus: ["part number match", "output type", "connector", "IP rating"]
    },
    {
      name: "PLCs & Automation",
      slug: "plcs-automation",
      summary: "Controllers, I/O, HMIs, relays, machine safety, and automation spares.",
      focus: ["platform family", "I/O count", "protocol", "lifecycle"]
    },
    {
      name: "Drives & Motors",
      slug: "drives-motors",
      summary: "VFDs, soft starters, servo drives, motor control, and replacement motors.",
      focus: ["power rating", "voltage", "enclosure", "communications"]
    },
    {
      name: "Bearings & Power Transmission",
      slug: "bearings-power-transmission",
      summary: "Bearings, belts, couplings, pulleys, sprockets, and rotating spares.",
      focus: ["dimensions", "seals", "load", "interchange"]
    },
    {
      name: "Pumps",
      slug: "pumps",
      summary: "Centrifugal, multistage, dosing, process, and utility pump families.",
      focus: ["flow", "head", "material", "seal"]
    },
    {
      name: "Valves & Flow Control",
      slug: "valves-flow-control",
      summary: "Solenoid, control, isolation, steam, pneumatic, and process valves.",
      focus: ["port size", "media", "pressure", "actuation"]
    },
    {
      name: "Pneumatics",
      slug: "pneumatics",
      summary: "Cylinders, solenoid valves, FRLs, fittings, tubing, and manifolds.",
      focus: ["bore", "stroke", "voltage", "mounting"]
    },
    {
      name: "Hydraulics",
      slug: "hydraulics",
      summary: "Pumps, motors, valves, hose, fittings, cylinders, and power-unit spares.",
      focus: ["pressure", "flow", "thread", "seal kit"]
    },
    {
      name: "Electrical & Control Panels",
      slug: "electrical-control-panels",
      summary: "Relays, contactors, terminal blocks, breakers, power supplies, and panel parts.",
      focus: ["coil voltage", "rating", "mounting", "standard"]
    },
    {
      name: "Cables & Connectivity",
      slug: "cables-connectivity",
      summary: "Industrial cable, M12 cordsets, fieldbus wiring, glands, and connectors.",
      focus: ["core count", "shielding", "jacket", "connector"]
    },
    {
      name: "Fasteners & Hardware",
      slug: "fasteners-hardware",
      summary: "Industrial fasteners, anchors, washers, locking hardware, and assembly items.",
      focus: ["grade", "thread", "coating", "standard"]
    },
    {
      name: "Tools & MRO",
      slug: "tools-mro",
      summary: "Test instruments, measuring tools, adhesives, lubricants, and maintenance consumables.",
      focus: ["range", "accuracy", "certificate", "application"]
    }
  ],

  sourceChannels: [
    {
      type: "OEM",
      title: "Official manufacturer pages",
      body: "Best for datasheets, manuals, lifecycle notices, certifications, configuration rules, and authorized partners.",
      url: "https://www.globalspec.com/"
    },
    {
      type: "Distributor",
      title: "Authorized distributors",
      body: "Best for genuine stock, warranty path, regional delivery, tax invoices, and small-quantity buying.",
      url: "https://www.rs-online.com/"
    },
    {
      type: "Marketplace",
      title: "Industrial marketplaces",
      body: "Useful for broad discovery, alternative suppliers, international availability, and difficult-to-find products.",
      url: "https://www.alibaba.com/"
    },
    {
      type: "RFQ",
      title: "Quote-first sourcing",
      body: "Useful for pumps, valves, obsolete parts, custom assemblies, bulk orders, and project procurement.",
      url: "https://www.thomasnet.com/"
    },
    {
      type: "Surplus",
      title: "Obsolete and surplus channels",
      body: "Useful for discontinued automation parts, urgent plant breakdowns, and replacement spares that OEMs no longer stock.",
      url: "https://www.radwell.com/"
    },
    {
      type: "Data",
      title: "Datasheet and specification indexes",
      body: "Useful for comparing specifications, validating dimensions, and finding alternates before contacting a supplier.",
      url: "https://www.directindustry.com/"
    }
  ],

  sourceDirectory: [
    {
      name: "RS",
      type: "Distributor",
      regions: ["Europe", "Middle East", "Asia"],
      bestFor: "Electrical, automation, MRO, tools, and same-week industrial procurement.",
      url: "https://www.rs-online.com/"
    },
    {
      name: "DigiKey",
      type: "Distributor",
      regions: ["North America", "Europe", "Asia"],
      bestFor: "Electronic components, sensors, relays, connectors, and datasheet-rich search.",
      url: "https://www.digikey.com/"
    },
    {
      name: "Mouser",
      type: "Distributor",
      regions: ["North America", "Europe", "Asia"],
      bestFor: "Electronics, automation components, connectors, semiconductors, and new designs.",
      url: "https://www.mouser.com/"
    },
    {
      name: "Newark",
      type: "Distributor",
      regions: ["North America"],
      bestFor: "Automation, electronics, test equipment, and industrial controls.",
      url: "https://www.newark.com/"
    },
    {
      name: "Grainger",
      type: "MRO",
      regions: ["North America"],
      bestFor: "MRO, tools, safety, pumps, motors, valves, and facility maintenance.",
      url: "https://www.grainger.com/"
    },
    {
      name: "Motion",
      type: "MRO",
      regions: ["North America"],
      bestFor: "Bearings, belts, power transmission, hydraulics, pneumatics, and repair parts.",
      url: "https://www.motion.com/"
    },
    {
      name: "TME",
      type: "Distributor",
      regions: ["Europe", "Middle East", "Asia"],
      bestFor: "Automation, electronics, electrical parts, and fast international catalog search.",
      url: "https://www.tme.com/"
    },
    {
      name: "Automation24",
      type: "Distributor",
      regions: ["Europe", "North America"],
      bestFor: "Sensors, controls, drives, pneumatics, and automation replacement parts.",
      url: "https://www.automation24.com/"
    },
    {
      name: "Galco",
      type: "Distributor",
      regions: ["North America"],
      bestFor: "Drives, motor controls, electrical repair parts, and industrial electronics.",
      url: "https://www.galco.com/"
    },
    {
      name: "Radwell",
      type: "Surplus",
      regions: ["North America", "Europe"],
      bestFor: "Obsolete automation spares, refurbished units, and urgent replacement parts.",
      url: "https://www.radwell.com/"
    },
    {
      name: "EU Automation",
      type: "Surplus",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      bestFor: "Automation spares, obsolete components, PLCs, HMIs, drives, and controls.",
      url: "https://www.euautomation.com/"
    },
    {
      name: "Thomasnet",
      type: "RFQ",
      regions: ["North America"],
      bestFor: "Supplier discovery, custom manufacturing, RFQs, pumps, valves, and industrial services.",
      url: "https://www.thomasnet.com/"
    },
    {
      name: "GlobalSpec",
      type: "Data",
      regions: ["Global"],
      bestFor: "Engineering datasheets, industrial product discovery, and specification comparison.",
      url: "https://www.globalspec.com/"
    },
    {
      name: "DirectIndustry",
      type: "Data",
      regions: ["Global"],
      bestFor: "OEM discovery, industrial equipment categories, datasheets, and product families.",
      url: "https://www.directindustry.com/"
    },
    {
      name: "IndustryStock",
      type: "Marketplace",
      regions: ["Europe", "Global"],
      bestFor: "Industrial supplier discovery, machinery, pumps, valves, and project sourcing.",
      url: "https://www.industrystock.com/"
    },
    {
      name: "Alibaba",
      type: "Marketplace",
      regions: ["Asia", "Global"],
      bestFor: "Broad international supplier discovery, bulk buying, private label, and RFQs.",
      url: "https://www.alibaba.com/"
    },
    {
      name: "IndiaMART",
      type: "Marketplace",
      regions: ["Asia", "Middle East"],
      bestFor: "India-based industrial suppliers, machinery, electrical parts, pumps, and tools.",
      url: "https://www.indiamart.com/"
    },
    {
      name: "MISUMI",
      type: "Distributor",
      regions: ["Asia", "North America", "Europe"],
      bestFor: "Mechanical components, factory automation parts, configurable components, and tooling.",
      url: "https://www.misumi-ec.com/"
    }
  ],

  products: [
    {
      id: "ifm-ie5338",
      name: "IE5338 Inductive Proximity Sensor",
      brand: "IFM",
      sku: "IE5338",
      category: "Sensors",
      family: "M12 inductive sensors",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Compact M12 inductive sensor for machine automation, position detection, and control cabinet retrofits.",
      applications: ["machine position detection", "conveyor sensing", "factory automation"],
      specs: ["M12", "PNP", "NO", "10-30 VDC", "IP67"],
      certifications: ["CE", "cULus"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 86,
      cost: 69,
      balanced: 91,
      lead: "2-7 days",
      moq: "1 pc",
      alternatives: ["SICK IME12", "Pepperl+Fuchs NBB", "Telemecanique XS"],
      sources: [
        { type: "OEM", name: "IFM", url: "https://www.ifm.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Surplus", name: "EU Automation", url: "https://www.euautomation.com/", region: "Global", action: "Check spare stock" }
      ]
    },
    {
      id: "sick-ime12",
      name: "IME12 Inductive Proximity Sensor",
      brand: "SICK",
      sku: "IME12",
      category: "Sensors",
      family: "Inductive sensor family",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial inductive sensor family for harsh environments, high switching accuracy, and compact machine builds.",
      applications: ["packaging equipment", "material handling", "machine safety support"],
      specs: ["M12", "PNP/NPN", "flush", "DC 3-wire", "IP67"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 82,
      cost: 66,
      balanced: 87,
      lead: "3-10 days",
      moq: "1 pc",
      alternatives: ["IFM IE5338", "Omron E2E", "Balluff BES"],
      sources: [
        { type: "OEM", name: "SICK", url: "https://www.sick.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "DigiKey", url: "https://www.digikey.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "Mouser", url: "https://www.mouser.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "omron-e2e",
      name: "E2E Cylindrical Proximity Sensor",
      brand: "Omron",
      sku: "E2E",
      category: "Sensors",
      family: "Cylindrical proximity sensors",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "General-purpose inductive proximity sensor series used widely in OEM equipment and maintenance replacements.",
      applications: ["machine detection", "tooling position", "automation spares"],
      specs: ["M8/M12/M18", "PNP/NPN", "shielded options", "prewired or connector"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 84,
      cost: 70,
      balanced: 88,
      lead: "2-10 days",
      moq: "1 pc",
      alternatives: ["IFM IE series", "SICK IME", "Pepperl+Fuchs NBB"],
      sources: [
        { type: "OEM", name: "Omron", url: "https://industrial.omron.eu/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "DigiKey", url: "https://www.digikey.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "Mouser", url: "https://www.mouser.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "siemens-s7-1200-1214c",
      name: "S7-1200 CPU 1214C Controller",
      brand: "Siemens",
      sku: "6ES7214",
      category: "PLCs & Automation",
      family: "SIMATIC S7-1200",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Compact PLC controller for small automation systems, machine builders, and control panel upgrades.",
      applications: ["machine control", "OEM automation", "small process skids"],
      specs: ["24 VDC", "digital I/O", "PROFINET", "compact PLC"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 72,
      cost: 58,
      balanced: 82,
      lead: "1-4 weeks",
      moq: "1 pc",
      alternatives: ["Schneider Modicon M221", "Allen-Bradley Micro850", "Omron CP2E"],
      sources: [
        { type: "OEM", name: "Siemens", url: "https://www.siemens.com/", region: "Global", action: "Product data" },
        { type: "Surplus", name: "Radwell", url: "https://www.radwell.com/", region: "North America, Europe", action: "Check stock" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "schneider-m221",
      name: "Modicon M221 Logic Controller",
      brand: "Schneider Electric",
      sku: "M221",
      category: "PLCs & Automation",
      family: "Modicon M221",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Compact controller for simple machines, remote I/O, packaging, pumping, and building equipment.",
      applications: ["small machines", "pump panels", "building automation"],
      specs: ["logic controller", "Ethernet options", "Modbus", "SoMachine Basic"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 76,
      cost: 64,
      balanced: 84,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["Siemens S7-1200", "Allen-Bradley Micro850", "Omron CP2E"],
      sources: [
        { type: "OEM", name: "Schneider Electric", url: "https://www.se.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Newark", url: "https://www.newark.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "allen-bradley-micro850",
      name: "Micro850 Programmable Controller",
      brand: "Allen-Bradley",
      sku: "2080-L50E",
      category: "PLCs & Automation",
      family: "Micro800",
      regions: ["North America", "Europe", "Middle East", "Asia"],
      description: "Micro PLC platform for stand-alone machines, Ethernet-connected control, and OEM equipment.",
      applications: ["stand-alone machines", "remote control panels", "small process equipment"],
      specs: ["Ethernet", "Micro PLC", "expandable I/O", "Connected Components Workbench"],
      certifications: ["CE", "cULus"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 70,
      cost: 57,
      balanced: 79,
      lead: "1-5 weeks",
      moq: "1 pc",
      alternatives: ["Siemens S7-1200", "Schneider M221", "Omron CP2E"],
      sources: [
        { type: "OEM", name: "Rockwell Automation", url: "https://www.rockwellautomation.com/", region: "Global", action: "Product data" },
        { type: "Surplus", name: "Radwell", url: "https://www.radwell.com/", region: "North America, Europe", action: "Check spare stock" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "abb-acs580",
      name: "ACS580 General Purpose Drive",
      brand: "ABB",
      sku: "ACS580",
      category: "Drives & Motors",
      family: "General purpose VFD",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Variable frequency drive for pumps, fans, conveyors, mixers, and general industrial motors.",
      applications: ["pump control", "fan control", "conveyors"],
      specs: ["VFD", "3-phase", "IP21/IP55", "Modbus", "energy optimizer"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 68,
      cost: 64,
      balanced: 80,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["Siemens G120", "Danfoss VLT", "Schneider Altivar"],
      sources: [
        { type: "OEM", name: "ABB", url: "https://global.abb/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Galco", url: "https://www.galco.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "Automation24", url: "https://www.automation24.com/", region: "Europe, North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "schneider-atv320",
      name: "Altivar Machine ATV320 Drive",
      brand: "Schneider Electric",
      sku: "ATV320",
      category: "Drives & Motors",
      family: "Altivar Machine",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Machine drive for asynchronous and synchronous motors in compact automation panels.",
      applications: ["machine drives", "material handling", "packaging equipment"],
      specs: ["VFD", "0.18-15 kW", "Modbus", "CANopen", "STO safety"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 74,
      cost: 61,
      balanced: 81,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["ABB ACS580", "Danfoss FC 51", "Siemens G120"],
      sources: [
        { type: "OEM", name: "Schneider Electric", url: "https://www.se.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Newark", url: "https://www.newark.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "siemens-g120",
      name: "SINAMICS G120 Modular Drive",
      brand: "Siemens",
      sku: "G120",
      category: "Drives & Motors",
      family: "SINAMICS G120",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Modular variable speed drive platform for industrial motor control, conveyors, pumps, and fans.",
      applications: ["conveyors", "pumps", "fans", "industrial motor control"],
      specs: ["VFD", "modular", "PROFINET options", "safety functions"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 66,
      cost: 56,
      balanced: 78,
      lead: "2-5 weeks",
      moq: "1 pc",
      alternatives: ["ABB ACS580", "Schneider ATV320", "Danfoss VLT"],
      sources: [
        { type: "OEM", name: "Siemens", url: "https://www.siemens.com/", region: "Global", action: "Product data" },
        { type: "Surplus", name: "EU Automation", url: "https://www.euautomation.com/", region: "Global", action: "Check spare stock" },
        { type: "Distributor", name: "Galco", url: "https://www.galco.com/", region: "North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "skf-6205-2rs1",
      name: "6205-2RS1 Deep Groove Ball Bearing",
      brand: "SKF",
      sku: "6205-2RS1",
      category: "Bearings & Power Transmission",
      family: "Deep groove ball bearings",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Sealed deep groove bearing for motors, pumps, gearboxes, fans, conveyors, and general rotating equipment.",
      applications: ["motor repair", "pump repair", "rotating equipment"],
      specs: ["25 mm bore", "52 mm OD", "15 mm width", "sealed", "steel"],
      certifications: ["ISO"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 92,
      cost: 78,
      balanced: 93,
      lead: "1-5 days",
      moq: "1 pc",
      alternatives: ["NSK 6205DDU", "FAG 6205-2RSR", "Timken 205PP"],
      sources: [
        { type: "OEM", name: "SKF", url: "https://www.skf.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Motion", url: "https://www.motion.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "Grainger", url: "https://www.grainger.com/", region: "North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "gates-spa",
      name: "SPA V-Belt",
      brand: "Gates",
      sku: "SPA",
      category: "Bearings & Power Transmission",
      family: "Wrapped metric V-belts",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Wrapped classical metric V-belt used in fans, compressors, conveyors, and industrial drives.",
      applications: ["fan drives", "compressors", "belt replacement"],
      specs: ["metric V-belt", "13 mm top width", "wrapped", "oil resistant"],
      certifications: ["ISO"],
      datasheet: true,
      verified: false,
      lifecycle: "Active",
      speed: 90,
      cost: 82,
      balanced: 88,
      lead: "1-7 days",
      moq: "1 pc",
      alternatives: ["Optibelt SK", "Continental Conti-V", "PIX SPA"],
      sources: [
        { type: "OEM", name: "Gates", url: "https://www.gates.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Motion", url: "https://www.motion.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Marketplace", name: "Zoro", url: "https://www.zoro.com/", region: "North America", action: "Buy or compare" }
      ]
    },
    {
      id: "nsk-6205ddu",
      name: "6205DDU Deep Groove Ball Bearing",
      brand: "NSK",
      sku: "6205DDU",
      category: "Bearings & Power Transmission",
      family: "Deep groove ball bearings",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Sealed deep groove bearing for electric motors, pumps, small gearboxes, and equipment maintenance.",
      applications: ["motor overhaul", "spares planning", "pump repair"],
      specs: ["25 mm bore", "52 mm OD", "15 mm width", "contact seals"],
      certifications: ["ISO"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 88,
      cost: 76,
      balanced: 89,
      lead: "1-7 days",
      moq: "1 pc",
      alternatives: ["SKF 6205-2RS1", "FAG 6205-2RSR", "Koyo 6205-2RS"],
      sources: [
        { type: "OEM", name: "NSK", url: "https://www.nsk.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Motion", url: "https://www.motion.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Marketplace", name: "MISUMI", url: "https://www.misumi-ec.com/", region: "Global", action: "Buy or configure" }
      ]
    },
    {
      id: "grundfos-cr",
      name: "CR Vertical Multistage Pump",
      brand: "Grundfos",
      sku: "CR",
      category: "Pumps",
      family: "Vertical multistage pumps",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Vertical multistage centrifugal pump platform for water treatment, pressure boosting, and process duty.",
      applications: ["water treatment", "pressure boosting", "industrial process water"],
      specs: ["vertical multistage", "stainless options", "IE motor", "mechanical seal"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 60,
      cost: 56,
      balanced: 75,
      lead: "2-6 weeks",
      moq: "1 unit",
      alternatives: ["Lowara e-SV", "KSB Movitec", "Wilo Helix"],
      sources: [
        { type: "OEM", name: "Grundfos", url: "https://www.grundfos.com/", region: "Global", action: "Product data" },
        { type: "RFQ", name: "Thomasnet", url: "https://www.thomasnet.com/", region: "North America", action: "Find suppliers" },
        { type: "Data", name: "GlobalSpec", url: "https://www.globalspec.com/", region: "Global", action: "Compare specs" }
      ]
    },
    {
      id: "ksb-etanorm",
      name: "Etanorm Standardized Pump",
      brand: "KSB",
      sku: "Etanorm",
      category: "Pumps",
      family: "Standardized water pumps",
      regions: ["Europe", "Middle East", "Asia"],
      description: "Standardized water pump family for utilities, HVAC, general industry, and process applications.",
      applications: ["HVAC", "water utilities", "general industry"],
      specs: ["centrifugal", "EN 733", "horizontal", "long-coupled"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 54,
      cost: 58,
      balanced: 72,
      lead: "3-8 weeks",
      moq: "1 unit",
      alternatives: ["Grundfos NB", "Wilo CronoNorm", "Lowara e-NSC"],
      sources: [
        { type: "OEM", name: "KSB", url: "https://www.ksb.com/", region: "Global", action: "Product data" },
        { type: "Marketplace", name: "IndustryStock", url: "https://www.industrystock.com/", region: "Europe, Global", action: "Find suppliers" },
        { type: "Marketplace", name: "Alibaba", url: "https://www.alibaba.com/", region: "Asia, Global", action: "Supplier discovery" }
      ]
    },
    {
      id: "lowara-esv",
      name: "e-SV Vertical Multistage Pump",
      brand: "Lowara",
      sku: "e-SV",
      category: "Pumps",
      family: "Vertical multistage pumps",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Stainless vertical multistage pump range for pressure boosting, HVAC, and industrial water systems.",
      applications: ["pressure boosting", "HVAC", "water supply"],
      specs: ["vertical multistage", "stainless steel", "mechanical seal", "IE motor"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 58,
      cost: 55,
      balanced: 73,
      lead: "2-6 weeks",
      moq: "1 unit",
      alternatives: ["Grundfos CR", "KSB Movitec", "Wilo Helix"],
      sources: [
        { type: "OEM", name: "Xylem Lowara", url: "https://www.xylem.com/", region: "Global", action: "Product data" },
        { type: "RFQ", name: "Thomasnet", url: "https://www.thomasnet.com/", region: "North America", action: "Find suppliers" },
        { type: "Data", name: "DirectIndustry", url: "https://www.directindustry.com/", region: "Global", action: "Compare specs" }
      ]
    },
    {
      id: "asco-8210",
      name: "8210 Solenoid Valve",
      brand: "ASCO",
      sku: "8210",
      category: "Valves & Flow Control",
      family: "General service solenoid valves",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "General service solenoid valve for air, inert gas, water, and light oil applications.",
      applications: ["water control", "air control", "utility skids"],
      specs: ["2-way", "brass", "NBR options", "AC/DC coils"],
      certifications: ["UL", "CSA"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 78,
      cost: 65,
      balanced: 84,
      lead: "3-14 days",
      moq: "1 pc",
      alternatives: ["Burkert 6213", "Parker Gold Ring", "Danfoss EV220B"],
      sources: [
        { type: "OEM", name: "Emerson", url: "https://www.emerson.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Grainger", url: "https://www.grainger.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "MSC", url: "https://www.mscdirect.com/", region: "North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "burkert-6213",
      name: "6213 EV Solenoid Valve",
      brand: "Burkert",
      sku: "6213 EV",
      category: "Valves & Flow Control",
      family: "Servo-assisted diaphragm valves",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Servo-assisted diaphragm valve for neutral liquids and gases in industrial systems.",
      applications: ["water systems", "compressed air", "process skids"],
      specs: ["2/2-way", "servo-assisted", "brass body", "DN 10-40"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 70,
      cost: 62,
      balanced: 80,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["ASCO 8210", "Gemu solenoid series", "Danfoss EV220B"],
      sources: [
        { type: "OEM", name: "Burkert", url: "https://www.burkert.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" }
      ]
    },
    {
      id: "spirax-ft14",
      name: "FT14 Ball Float Steam Trap",
      brand: "Spirax Sarco",
      sku: "FT14",
      category: "Valves & Flow Control",
      family: "Steam traps",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Ball float steam trap family for process steam systems, heat exchangers, and condensate removal.",
      applications: ["steam systems", "heat exchangers", "process plants"],
      specs: ["ball float", "cast iron options", "flanged/threaded", "condensate duty"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 58,
      cost: 57,
      balanced: 74,
      lead: "2-5 weeks",
      moq: "1 pc",
      alternatives: ["Armstrong 800 series", "TLV J3X", "Watson McDaniel FT"],
      sources: [
        { type: "OEM", name: "Spirax Sarco", url: "https://www.spiraxsarco.com/", region: "Global", action: "Product data" },
        { type: "RFQ", name: "Thomasnet", url: "https://www.thomasnet.com/", region: "North America", action: "Find suppliers" },
        { type: "Data", name: "DirectIndustry", url: "https://www.directindustry.com/", region: "Global", action: "Compare specs" }
      ]
    },
    {
      id: "festo-dsbc",
      name: "DSBC Pneumatic Cylinder",
      brand: "Festo",
      sku: "DSBC",
      category: "Pneumatics",
      family: "ISO pneumatic cylinders",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "ISO pneumatic actuator family for factory automation, packaging, and material handling.",
      applications: ["linear motion", "packaging", "material handling"],
      specs: ["ISO 15552", "double-acting", "magnetic piston", "adjustable cushioning"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 77,
      cost: 63,
      balanced: 84,
      lead: "1-2 weeks",
      moq: "1 pc",
      alternatives: ["SMC CP96", "Norgren PRA", "Parker P1D"],
      sources: [
        { type: "OEM", name: "Festo", url: "https://www.festo.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" },
        { type: "Distributor", name: "Automation24", url: "https://www.automation24.com/", region: "Europe, North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "smc-sy5000",
      name: "SY5000 Solenoid Valve",
      brand: "SMC",
      sku: "SY5000",
      category: "Pneumatics",
      family: "Directional control valves",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Compact directional control solenoid valve for pneumatic manifolds and automation systems.",
      applications: ["valve manifolds", "pneumatic automation", "machine control"],
      specs: ["5-port", "24 VDC", "manifold mount", "low power"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 80,
      cost: 67,
      balanced: 85,
      lead: "3-14 days",
      moq: "1 pc",
      alternatives: ["Festo VUVG", "Norgren V60", "Parker Viking Xtreme"],
      sources: [
        { type: "OEM", name: "SMC", url: "https://www.smcworld.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "Grainger", url: "https://www.grainger.com/", region: "North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "norgren-pra",
      name: "PRA Profile Pneumatic Cylinder",
      brand: "Norgren",
      sku: "PRA",
      category: "Pneumatics",
      family: "ISO/VDMA pneumatic cylinders",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Profile pneumatic cylinder range for compact machine automation and factory equipment.",
      applications: ["factory automation", "actuation", "machine spares"],
      specs: ["ISO/VDMA", "double-acting", "profile tube", "magnetic piston"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 74,
      cost: 62,
      balanced: 81,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["Festo DSBC", "SMC CP96", "Parker P1D"],
      sources: [
        { type: "OEM", name: "Norgren", url: "https://www.norgren.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "RFQ", name: "Thomasnet", url: "https://www.thomasnet.com/", region: "North America", action: "Find suppliers" }
      ]
    },
    {
      id: "bosch-rexroth-a10vso",
      name: "A10VSO Axial Piston Pump",
      brand: "Bosch Rexroth",
      sku: "A10VSO",
      category: "Hydraulics",
      family: "Axial piston pumps",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Variable displacement axial piston pump for open-circuit industrial hydraulic systems.",
      applications: ["hydraulic power units", "presses", "industrial machinery"],
      specs: ["open circuit", "variable displacement", "swashplate", "industrial hydraulics"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 48,
      cost: 50,
      balanced: 70,
      lead: "4-12 weeks",
      moq: "1 unit",
      alternatives: ["Parker PVplus", "Eaton Vickers PVB", "Danfoss Series 45"],
      sources: [
        { type: "OEM", name: "Bosch Rexroth", url: "https://www.boschrexroth.com/", region: "Global", action: "Product data" },
        { type: "RFQ", name: "Hydraulics Online", url: "https://hydraulicsonline.com/", region: "Global", action: "RFQ" },
        { type: "Marketplace", name: "Surplus Center", url: "https://www.surpluscenter.com/", region: "North America", action: "Check surplus" }
      ]
    },
    {
      id: "parker-43-series",
      name: "43 Series Hydraulic Hose Fitting",
      brand: "Parker",
      sku: "43 Series",
      category: "Hydraulics",
      family: "Crimp hose fittings",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Crimp-style hydraulic hose fitting family for field service, mobile equipment, and MRO use.",
      applications: ["hydraulic hose repair", "field service", "mobile equipment"],
      specs: ["crimp fitting", "steel", "multiple ends", "no-skive options"],
      certifications: ["SAE"],
      datasheet: true,
      verified: false,
      lifecycle: "Active",
      speed: 88,
      cost: 73,
      balanced: 86,
      lead: "1-10 days",
      moq: "1 pc",
      alternatives: ["Gates MegaCrimp", "Eaton Winner", "Manuli fittings"],
      sources: [
        { type: "OEM", name: "Parker", url: "https://www.parker.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Motion", url: "https://www.motion.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "MSC", url: "https://www.mscdirect.com/", region: "North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "eaton-char-lynn-2000",
      name: "Char-Lynn 2000 Series Hydraulic Motor",
      brand: "Eaton",
      sku: "2000 Series",
      category: "Hydraulics",
      family: "Low-speed high-torque motors",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Hydraulic motor family used in mobile equipment, conveyors, winches, and industrial machinery.",
      applications: ["mobile equipment", "conveyors", "winches"],
      specs: ["LSHT motor", "orbital", "multiple displacements", "hydraulic drive"],
      certifications: ["ISO"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 52,
      cost: 55,
      balanced: 72,
      lead: "3-8 weeks",
      moq: "1 unit",
      alternatives: ["Danfoss OMP", "Parker Torqmotor", "White Drive motor"],
      sources: [
        { type: "OEM", name: "Eaton", url: "https://www.eaton.com/", region: "Global", action: "Product data" },
        { type: "RFQ", name: "Hydraulics Online", url: "https://hydraulicsonline.com/", region: "Global", action: "RFQ" },
        { type: "Marketplace", name: "Surplus Center", url: "https://www.surpluscenter.com/", region: "North America", action: "Check surplus" }
      ]
    },
    {
      id: "omron-my2n",
      name: "MY2N General Purpose Relay",
      brand: "Omron",
      sku: "MY2N",
      category: "Electrical & Control Panels",
      family: "Plug-in industrial relays",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Plug-in industrial relay for panels, controls, interlocks, and machine service replacements.",
      applications: ["control panels", "interlocks", "service replacements"],
      specs: ["DPDT", "socket mount", "LED options", "AC/DC coils"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 93,
      cost: 80,
      balanced: 94,
      lead: "1-5 days",
      moq: "1 pc",
      alternatives: ["Finder 55 series", "Schneider RXM", "Phoenix Contact relay"],
      sources: [
        { type: "OEM", name: "Omron", url: "https://industrial.omron.eu/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Mouser", url: "https://www.mouser.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "DigiKey", url: "https://www.digikey.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "phoenix-pt",
      name: "PT Push-In Terminal Block",
      brand: "Phoenix Contact",
      sku: "PT",
      category: "Electrical & Control Panels",
      family: "Push-in terminal blocks",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Push-in terminal block system for control cabinets, machinery, and distribution panels.",
      applications: ["control cabinets", "machine wiring", "panel building"],
      specs: ["push-in", "DIN rail", "modular", "IEC rated"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 89,
      cost: 76,
      balanced: 91,
      lead: "1-7 days",
      moq: "1 pc",
      alternatives: ["Wago 2002", "Weidmuller A-series", "Conta-Clip PRK"],
      sources: [
        { type: "OEM", name: "Phoenix Contact", url: "https://www.phoenixcontact.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "DigiKey", url: "https://www.digikey.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" }
      ]
    },
    {
      id: "schneider-lc1d",
      name: "TeSys D Contactor",
      brand: "Schneider Electric",
      sku: "LC1D",
      category: "Electrical & Control Panels",
      family: "Motor control contactors",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial contactor family for motor control, HVAC panels, pumping panels, and OEM machines.",
      applications: ["motor starters", "HVAC panels", "pump control"],
      specs: ["AC-3 duty", "AC/DC coils", "DIN rail", "auxiliary options"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 82,
      cost: 68,
      balanced: 86,
      lead: "2-10 days",
      moq: "1 pc",
      alternatives: ["Siemens Sirius 3RT", "ABB AF", "Eaton DILM"],
      sources: [
        { type: "OEM", name: "Schneider Electric", url: "https://www.se.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "Grainger", url: "https://www.grainger.com/", region: "North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "lapp-olflex-110",
      name: "OLFLEX Classic 110 Control Cable",
      brand: "LAPP",
      sku: "OLFLEX Classic 110",
      category: "Cables & Connectivity",
      family: "Control cable",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Flexible PVC control cable for machinery, control cabinets, and general industrial wiring.",
      applications: ["control wiring", "machine wiring", "panel building"],
      specs: ["PVC", "numbered cores", "flexible", "oil resistant options"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 78,
      cost: 70,
      balanced: 84,
      lead: "3-14 days",
      moq: "cut length or reel",
      alternatives: ["Belden control cable", "Helukabel JZ-500", "Prysmian control cable"],
      sources: [
        { type: "OEM", name: "LAPP", url: "https://www.lapp.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Marketplace", name: "IndustryStock", url: "https://www.industrystock.com/", region: "Europe, Global", action: "Find suppliers" }
      ]
    },
    {
      id: "belden-8723",
      name: "8723 Shielded Instrumentation Cable",
      brand: "Belden",
      sku: "8723",
      category: "Cables & Connectivity",
      family: "Instrumentation cable",
      regions: ["North America", "Europe", "Middle East", "Asia"],
      description: "Shielded twisted-pair instrumentation cable used for industrial controls, sensors, and analog signals.",
      applications: ["instrumentation", "analog signals", "control systems"],
      specs: ["shielded", "twisted pair", "300 V", "PVC jacket"],
      certifications: ["UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 76,
      cost: 67,
      balanced: 82,
      lead: "2-10 days",
      moq: "cut length or reel",
      alternatives: ["Alpha Wire equivalent", "LAPP instrumentation cable", "Prysmian signal cable"],
      sources: [
        { type: "OEM", name: "Belden", url: "https://www.belden.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Newark", url: "https://www.newark.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "DigiKey", url: "https://www.digikey.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "murr-m12-cordset",
      name: "M12 Sensor Actuator Cordset",
      brand: "Murr Elektronik",
      sku: "M12 Cordset",
      category: "Cables & Connectivity",
      family: "M12 connectivity",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial M12 cordset family for sensor and actuator wiring in factory automation environments.",
      applications: ["sensor wiring", "actuator wiring", "field connectivity"],
      specs: ["M12", "A-coded options", "PUR/PVC", "straight or angled"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 84,
      cost: 72,
      balanced: 87,
      lead: "2-10 days",
      moq: "1 pc",
      alternatives: ["Phoenix Contact SAC", "Turck cordset", "Balluff BCC"],
      sources: [
        { type: "OEM", name: "Murr Elektronik", url: "https://www.murrelektronik.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Automation24", url: "https://www.automation24.com/", region: "Europe, North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" }
      ]
    },
    {
      id: "unbrako-shcs",
      name: "Socket Head Cap Screw",
      brand: "Unbrako",
      sku: "SHCS",
      category: "Fasteners & Hardware",
      family: "High-tensile socket screws",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "High-tensile socket head cap screws for machinery, tooling, maintenance, and assembly.",
      applications: ["machine assembly", "tooling", "maintenance"],
      specs: ["socket head", "12.9 options", "metric and inch", "alloy steel"],
      certifications: ["ISO", "DIN"],
      datasheet: false,
      verified: true,
      lifecycle: "Active",
      speed: 86,
      cost: 80,
      balanced: 88,
      lead: "1-7 days",
      moq: "box quantity",
      alternatives: ["Holo-Krome SHCS", "Bossard SHCS", "Fabory SHCS"],
      sources: [
        { type: "OEM", name: "Unbrako", url: "https://www.unbrako.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "MSC", url: "https://www.mscdirect.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Marketplace", name: "MISUMI", url: "https://www.misumi-ec.com/", region: "Global", action: "Buy or configure" }
      ]
    },
    {
      id: "nord-lock-washer",
      name: "Wedge-Locking Washer Pair",
      brand: "Nord-Lock",
      sku: "NL",
      category: "Fasteners & Hardware",
      family: "Wedge-locking washers",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Wedge-locking washer pair designed to secure bolted joints exposed to vibration and dynamic loads.",
      applications: ["vibration joints", "rotating equipment", "heavy equipment"],
      specs: ["wedge-locking", "pair", "steel/stainless options", "metric and inch"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 72,
      cost: 60,
      balanced: 79,
      lead: "1-3 weeks",
      moq: "pack quantity",
      alternatives: ["Schnorr safety washer", "Heico-Lock", "Belleville washer"],
      sources: [
        { type: "OEM", name: "Nord-Lock", url: "https://www.nord-lock.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Motion", url: "https://www.motion.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Marketplace", name: "IndustryStock", url: "https://www.industrystock.com/", region: "Europe, Global", action: "Find suppliers" }
      ]
    },
    {
      id: "hilti-hst3",
      name: "HST3 Wedge Anchor",
      brand: "Hilti",
      sku: "HST3",
      category: "Fasteners & Hardware",
      family: "Mechanical anchors",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "High-performance wedge anchor for concrete fastening in industrial, commercial, and infrastructure projects.",
      applications: ["concrete anchoring", "equipment baseplates", "steel supports"],
      specs: ["wedge anchor", "ETA options", "carbon/stainless options", "concrete fastening"],
      certifications: ["ETA", "ICC-ES options"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 70,
      cost: 58,
      balanced: 77,
      lead: "1-3 weeks",
      moq: "box quantity",
      alternatives: ["Fischer FAZ II", "Rawlplug R-HPTII", "Powers wedge anchor"],
      sources: [
        { type: "OEM", name: "Hilti", url: "https://www.hilti.com/", region: "Global", action: "Product data" },
        { type: "Marketplace", name: "IndiaMART", url: "https://www.indiamart.com/", region: "Asia, Middle East", action: "Find suppliers" },
        { type: "RFQ", name: "Thomasnet", url: "https://www.thomasnet.com/", region: "North America", action: "Find suppliers" }
      ]
    },
    {
      id: "fluke-87v",
      name: "87V Industrial Multimeter",
      brand: "Fluke",
      sku: "87V",
      category: "Tools & MRO",
      family: "Industrial multimeters",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial true-RMS digital multimeter used by maintenance technicians for electrical troubleshooting.",
      applications: ["electrical maintenance", "troubleshooting", "commissioning"],
      specs: ["true RMS", "CAT III/IV", "temperature", "frequency"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 90,
      cost: 68,
      balanced: 88,
      lead: "1-7 days",
      moq: "1 pc",
      alternatives: ["Keysight U1282A", "Hioki DT4282", "Amprobe HD160C"],
      sources: [
        { type: "OEM", name: "Fluke", url: "https://www.fluke.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Grainger", url: "https://www.grainger.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "mitutoyo-500-caliper",
      name: "500 Series Digital Caliper",
      brand: "Mitutoyo",
      sku: "500 Series",
      category: "Tools & MRO",
      family: "Digital calipers",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Digital caliper series for quality control, maintenance measurement, and workshop inspection.",
      applications: ["quality control", "maintenance measurement", "inspection"],
      specs: ["digital", "stainless steel", "0-150 mm options", "ABS scale"],
      certifications: ["ISO calibration options"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 86,
      cost: 69,
      balanced: 85,
      lead: "1-10 days",
      moq: "1 pc",
      alternatives: ["Mahr MarCal", "Starrett digital caliper", "Insize digital caliper"],
      sources: [
        { type: "OEM", name: "Mitutoyo", url: "https://www.mitutoyo.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "MSC", url: "https://www.mscdirect.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Marketplace", name: "MISUMI", url: "https://www.misumi-ec.com/", region: "Global", action: "Buy or configure" }
      ]
    },
    {
      id: "loctite-243",
      name: "243 Medium Strength Threadlocker",
      brand: "Loctite",
      sku: "243",
      category: "Tools & MRO",
      family: "Threadlocker adhesive",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Medium-strength threadlocker for securing threaded fasteners while allowing hand-tool disassembly.",
      applications: ["bolt locking", "maintenance repair", "pump and motor service"],
      specs: ["medium strength", "oil tolerant", "blue", "anaerobic adhesive"],
      certifications: ["RoHS"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 94,
      cost: 81,
      balanced: 93,
      lead: "1-5 days",
      moq: "1 bottle",
      alternatives: ["Loctite 242", "Permatex blue threadlocker", "3M Scotch-Weld threadlocker"],
      sources: [
        { type: "OEM", name: "Henkel Adhesives", url: "https://www.henkel-adhesives.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Marketplace", name: "Zoro", url: "https://www.zoro.com/", region: "North America", action: "Buy or compare" }
      ]
    },
    {
      id: "pepperl-fuchs-nbb",
      name: "NBB Inductive Proximity Sensor",
      brand: "Pepperl+Fuchs",
      sku: "NBB",
      category: "Sensors",
      family: "Inductive proximity sensors",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial inductive sensor family for machine position feedback, conveyor detection, and plant maintenance replacements.",
      applications: ["position detection", "conveyor automation", "machine spares"],
      specs: ["M8/M12/M18 options", "flush and non-flush", "DC output", "connector options"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 80,
      cost: 67,
      balanced: 86,
      lead: "3-14 days",
      moq: "1 pc",
      alternatives: ["IFM IE series", "SICK IME", "Omron E2E"],
      sources: [
        { type: "OEM", name: "Pepperl+Fuchs", url: "https://www.pepperl-fuchs.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" }
      ]
    },
    {
      id: "balluff-bes",
      name: "BES Inductive Proximity Sensor",
      brand: "Balluff",
      sku: "BES",
      category: "Sensors",
      family: "Inductive sensor platform",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Inductive proximity sensor platform for factory automation, tooling position checks, and replacement sensor sourcing.",
      applications: ["factory automation", "tooling position", "robot cells"],
      specs: ["M12 options", "PNP/NPN variants", "shielded options", "IP67"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 78,
      cost: 65,
      balanced: 84,
      lead: "3-14 days",
      moq: "1 pc",
      alternatives: ["SICK IME12", "IFM IE5338", "Pepperl+Fuchs NBB"],
      sources: [
        { type: "OEM", name: "Balluff", url: "https://www.balluff.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Automation24", url: "https://www.automation24.com/", region: "Europe, North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" }
      ]
    },
    {
      id: "omron-cp2e",
      name: "CP2E Compact PLC",
      brand: "Omron",
      sku: "CP2E",
      category: "PLCs & Automation",
      family: "Compact machine controllers",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Compact PLC platform for small machine control, serial communication, and economical panel automation.",
      applications: ["small machines", "pump controls", "machine retrofits"],
      specs: ["compact PLC", "Ethernet options", "serial options", "CX-Programmer"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 74,
      cost: 66,
      balanced: 83,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["Schneider M221", "Siemens S7-1200", "Allen-Bradley Micro850"],
      sources: [
        { type: "OEM", name: "Omron", url: "https://industrial.omron.eu/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Mouser", url: "https://www.mouser.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "DigiKey", url: "https://www.digikey.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "wago-750",
      name: "750 Series Remote I/O System",
      brand: "WAGO",
      sku: "750 Series",
      category: "PLCs & Automation",
      family: "Modular remote I/O",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Modular I/O system for distributed automation, machine controls, process signals, and cabinet expansion.",
      applications: ["remote I/O", "process signals", "machine expansion"],
      specs: ["modular I/O", "fieldbus couplers", "digital and analog modules", "DIN rail"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 70,
      cost: 60,
      balanced: 80,
      lead: "1-4 weeks",
      moq: "1 pc",
      alternatives: ["Phoenix Contact Axioline", "Beckhoff EtherCAT I/O", "Siemens ET 200"],
      sources: [
        { type: "OEM", name: "WAGO", url: "https://www.wago.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "DigiKey", url: "https://www.digikey.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" }
      ]
    },
    {
      id: "danfoss-fc51",
      name: "VLT Micro Drive FC 51",
      brand: "Danfoss",
      sku: "FC 51",
      category: "Drives & Motors",
      family: "Micro variable frequency drives",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Compact VFD for small motors, conveyors, fans, pumps, and OEM machine panels.",
      applications: ["small motor control", "fans", "conveyors"],
      specs: ["VFD", "compact", "single and three phase options", "Modbus"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 76,
      cost: 69,
      balanced: 85,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["Schneider ATV320", "ABB ACS355", "Siemens G120C"],
      sources: [
        { type: "OEM", name: "Danfoss", url: "https://www.danfoss.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Galco", url: "https://www.galco.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Surplus", name: "EU Automation", url: "https://www.euautomation.com/", region: "Global", action: "Check spare stock" }
      ]
    },
    {
      id: "sew-eurodrive-drx",
      name: "DRN/DR2S AC Gearmotor",
      brand: "SEW-Eurodrive",
      sku: "DRN/DR2S",
      category: "Drives & Motors",
      family: "AC gearmotor platform",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Configurable industrial gearmotor platform for conveyors, packaging equipment, mixers, and material handling.",
      applications: ["conveyors", "material handling", "packaging equipment"],
      specs: ["AC gearmotor", "gearbox options", "brake options", "mounting variants"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 50,
      cost: 54,
      balanced: 72,
      lead: "3-10 weeks",
      moq: "1 unit",
      alternatives: ["Nord gearmotor", "Bonfiglioli gearmotor", "Lenze gearmotor"],
      sources: [
        { type: "OEM", name: "SEW-Eurodrive", url: "https://www.sew-eurodrive.com/", region: "Global", action: "Product data" },
        { type: "RFQ", name: "Thomasnet", url: "https://www.thomasnet.com/", region: "North America", action: "Find suppliers" },
        { type: "Data", name: "DirectIndustry", url: "https://www.directindustry.com/", region: "Global", action: "Compare specs" }
      ]
    },
    {
      id: "fag-6205-2rsr",
      name: "6205-2RSR Deep Groove Ball Bearing",
      brand: "FAG",
      sku: "6205-2RSR",
      category: "Bearings & Power Transmission",
      family: "Deep groove ball bearings",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Sealed deep groove bearing used for motors, pumps, fans, small gearboxes, and general rotating equipment.",
      applications: ["motor repair", "pump repair", "equipment maintenance"],
      specs: ["25 mm bore", "52 mm OD", "15 mm width", "sealed"],
      certifications: ["ISO"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 88,
      cost: 76,
      balanced: 90,
      lead: "1-7 days",
      moq: "1 pc",
      alternatives: ["SKF 6205-2RS1", "NSK 6205DDU", "Timken 205PP"],
      sources: [
        { type: "OEM", name: "Schaeffler", url: "https://www.schaeffler.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Motion", url: "https://www.motion.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "Grainger", url: "https://www.grainger.com/", region: "North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "optibelt-spa",
      name: "Optibelt SK SPA V-Belt",
      brand: "Optibelt",
      sku: "SPA",
      category: "Bearings & Power Transmission",
      family: "Wrapped wedge belts",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Wrapped wedge belt family for industrial fans, compressors, conveyors, and drive maintenance.",
      applications: ["belt replacement", "fan drives", "industrial drives"],
      specs: ["SPA profile", "wrapped belt", "metric lengths", "oil resistant options"],
      certifications: ["ISO"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 86,
      cost: 78,
      balanced: 87,
      lead: "1-10 days",
      moq: "1 pc",
      alternatives: ["Gates SPA", "Continental Conti-V", "PIX SPA"],
      sources: [
        { type: "OEM", name: "Optibelt", url: "https://www.optibelt.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Motion", url: "https://www.motion.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Marketplace", name: "IndustryStock", url: "https://www.industrystock.com/", region: "Europe, Global", action: "Find suppliers" }
      ]
    },
    {
      id: "wilo-helix",
      name: "Helix Vertical Multistage Pump",
      brand: "Wilo",
      sku: "Helix",
      category: "Pumps",
      family: "Vertical multistage pumps",
      regions: ["Europe", "Middle East", "Asia"],
      description: "Vertical multistage pump family for pressure boosting, HVAC, process water, and utility systems.",
      applications: ["pressure boosting", "HVAC", "process water"],
      specs: ["vertical multistage", "stainless options", "mechanical seal", "IE motor"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 56,
      cost: 55,
      balanced: 73,
      lead: "2-6 weeks",
      moq: "1 unit",
      alternatives: ["Grundfos CR", "Lowara e-SV", "KSB Movitec"],
      sources: [
        { type: "OEM", name: "Wilo", url: "https://wilo.com/", region: "Global", action: "Product data" },
        { type: "Data", name: "DirectIndustry", url: "https://www.directindustry.com/", region: "Global", action: "Compare specs" },
        { type: "Marketplace", name: "IndustryStock", url: "https://www.industrystock.com/", region: "Europe, Global", action: "Find suppliers" }
      ]
    },
    {
      id: "ebara-3m",
      name: "3M Stainless Centrifugal Pump",
      brand: "Ebara",
      sku: "3M",
      category: "Pumps",
      family: "Stainless centrifugal pumps",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Stainless centrifugal pump family for water transfer, washdown systems, light process duty, and utility skids.",
      applications: ["water transfer", "washdown", "light process duty"],
      specs: ["centrifugal", "stainless steel", "mechanical seal", "close-coupled"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 62,
      cost: 61,
      balanced: 76,
      lead: "2-5 weeks",
      moq: "1 unit",
      alternatives: ["Lowara CEA", "Grundfos CM", "KSB Etabloc"],
      sources: [
        { type: "OEM", name: "Ebara", url: "https://www.ebara.com/", region: "Global", action: "Product data" },
        { type: "RFQ", name: "Thomasnet", url: "https://www.thomasnet.com/", region: "North America", action: "Find suppliers" },
        { type: "Data", name: "GlobalSpec", url: "https://www.globalspec.com/", region: "Global", action: "Compare specs" }
      ]
    },
    {
      id: "danfoss-ev220b",
      name: "EV220B Solenoid Valve",
      brand: "Danfoss",
      sku: "EV220B",
      category: "Valves & Flow Control",
      family: "Servo-operated solenoid valves",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial solenoid valve family for water, air, oil, cooling circuits, and utility skids.",
      applications: ["water control", "cooling circuits", "utility skids"],
      specs: ["2-way", "servo-operated", "brass options", "AC/DC coils"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 76,
      cost: 67,
      balanced: 83,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["ASCO 8210", "Burkert 6213", "Parker solenoid valve"],
      sources: [
        { type: "OEM", name: "Danfoss", url: "https://www.danfoss.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" }
      ]
    },
    {
      id: "smc-vx2",
      name: "VX2 Direct Operated Solenoid Valve",
      brand: "SMC",
      sku: "VX2",
      category: "Valves & Flow Control",
      family: "Direct operated solenoid valves",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Direct operated solenoid valve series for air, water, vacuum, and light industrial fluid control.",
      applications: ["air control", "water control", "compact machines"],
      specs: ["2-way", "direct operated", "brass and stainless options", "AC/DC coils"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 78,
      cost: 68,
      balanced: 84,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["ASCO 8210", "Danfoss EV220B", "Burkert 6013"],
      sources: [
        { type: "OEM", name: "SMC", url: "https://www.smcworld.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "RFQ", name: "Thomasnet", url: "https://www.thomasnet.com/", region: "North America", action: "Find suppliers" }
      ]
    },
    {
      id: "festo-vuvg",
      name: "VUVG Solenoid Valve",
      brand: "Festo",
      sku: "VUVG",
      category: "Pneumatics",
      family: "Compact pneumatic valves",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Compact pneumatic solenoid valve range for valve terminals, machine automation, and replacement pneumatic spares.",
      applications: ["valve terminals", "machine automation", "pneumatic spares"],
      specs: ["5/2 and 5/3 options", "24 VDC coils", "manifold options", "compact body"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 78,
      cost: 65,
      balanced: 84,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["SMC SY5000", "Norgren V60", "Parker Viking Lite"],
      sources: [
        { type: "OEM", name: "Festo", url: "https://www.festo.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Automation24", url: "https://www.automation24.com/", region: "Europe, North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "parker-p1d",
      name: "P1D Pneumatic Cylinder",
      brand: "Parker",
      sku: "P1D",
      category: "Pneumatics",
      family: "ISO pneumatic cylinders",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "ISO pneumatic cylinder platform for automation, machine actuation, and service replacement duty.",
      applications: ["machine actuation", "factory automation", "service replacements"],
      specs: ["ISO cylinder", "double-acting", "magnetic piston", "mounting accessories"],
      certifications: ["CE"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 72,
      cost: 63,
      balanced: 80,
      lead: "1-4 weeks",
      moq: "1 pc",
      alternatives: ["Festo DSBC", "SMC CP96", "Norgren PRA"],
      sources: [
        { type: "OEM", name: "Parker", url: "https://www.parker.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Motion", url: "https://www.motion.com/", region: "North America", action: "Buy or RFQ" },
        { type: "RFQ", name: "Thomasnet", url: "https://www.thomasnet.com/", region: "North America", action: "Find suppliers" }
      ]
    },
    {
      id: "danfoss-omp",
      name: "OMP Orbital Hydraulic Motor",
      brand: "Danfoss",
      sku: "OMP",
      category: "Hydraulics",
      family: "Orbital hydraulic motors",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Low-speed high-torque orbital motor family for mobile equipment, conveyors, augers, and industrial drives.",
      applications: ["mobile equipment", "conveyors", "hydraulic drives"],
      specs: ["orbital motor", "multiple displacements", "LSHT", "shaft options"],
      certifications: ["ISO"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 56,
      cost: 58,
      balanced: 74,
      lead: "2-8 weeks",
      moq: "1 unit",
      alternatives: ["Eaton Char-Lynn 2000", "Parker Torqmotor", "White Drive motor"],
      sources: [
        { type: "OEM", name: "Danfoss", url: "https://www.danfoss.com/", region: "Global", action: "Product data" },
        { type: "RFQ", name: "Hydraulics Online", url: "https://hydraulicsonline.com/", region: "Global", action: "RFQ" },
        { type: "Marketplace", name: "Surplus Center", url: "https://www.surpluscenter.com/", region: "North America", action: "Check surplus" }
      ]
    },
    {
      id: "eaton-vickers-v10",
      name: "Vickers V10 Vane Pump",
      brand: "Eaton",
      sku: "V10",
      category: "Hydraulics",
      family: "Fixed displacement vane pumps",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial vane pump family used in hydraulic power units, machine tools, presses, and service replacements.",
      applications: ["hydraulic power units", "machine tools", "presses"],
      specs: ["vane pump", "fixed displacement", "industrial hydraulics", "shaft options"],
      certifications: ["ISO"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 54,
      cost: 57,
      balanced: 73,
      lead: "2-8 weeks",
      moq: "1 unit",
      alternatives: ["Parker Denison vane pump", "Bosch Rexroth vane pump", "Yuken PV2R"],
      sources: [
        { type: "OEM", name: "Eaton", url: "https://www.eaton.com/", region: "Global", action: "Product data" },
        { type: "RFQ", name: "Hydraulics Online", url: "https://hydraulicsonline.com/", region: "Global", action: "RFQ" },
        { type: "Marketplace", name: "Surplus Center", url: "https://www.surpluscenter.com/", region: "North America", action: "Check surplus" }
      ]
    },
    {
      id: "siemens-3rt",
      name: "SIRIUS 3RT Contactor",
      brand: "Siemens",
      sku: "3RT",
      category: "Electrical & Control Panels",
      family: "Motor control contactors",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial contactor family for motor starters, control panels, HVAC systems, and machine builders.",
      applications: ["motor starters", "control panels", "HVAC systems"],
      specs: ["AC-3 duty", "AC/DC coil options", "DIN rail", "auxiliary contacts"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 80,
      cost: 67,
      balanced: 85,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["Schneider LC1D", "ABB AF", "Eaton DILM"],
      sources: [
        { type: "OEM", name: "Siemens", url: "https://www.siemens.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Surplus", name: "Radwell", url: "https://www.radwell.com/", region: "North America, Europe", action: "Check spare stock" }
      ]
    },
    {
      id: "wago-2002",
      name: "2002 Series Push-In Terminal Block",
      brand: "WAGO",
      sku: "2002 Series",
      category: "Electrical & Control Panels",
      family: "TOPJOB S terminal blocks",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Push-in terminal block series for control cabinets, distribution panels, and machine wiring.",
      applications: ["panel wiring", "control cabinets", "machine wiring"],
      specs: ["push-in", "DIN rail", "jumper options", "marking options"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 88,
      cost: 77,
      balanced: 90,
      lead: "1-7 days",
      moq: "1 pc",
      alternatives: ["Phoenix Contact PT", "Weidmuller A-series", "Conta-Clip PRK"],
      sources: [
        { type: "OEM", name: "WAGO", url: "https://www.wago.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "DigiKey", url: "https://www.digikey.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" }
      ]
    },
    {
      id: "turck-rk4t",
      name: "RK 4T M12 Cordset",
      brand: "Turck",
      sku: "RK 4T",
      category: "Cables & Connectivity",
      family: "M12 sensor cordsets",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial M12 cordset family for sensor, actuator, and field device connectivity in automation systems.",
      applications: ["sensor wiring", "field connectivity", "machine spares"],
      specs: ["M12", "A-coded options", "PUR/PVC options", "straight connector"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 82,
      cost: 70,
      balanced: 86,
      lead: "2-10 days",
      moq: "1 pc",
      alternatives: ["Murr M12 cordset", "Phoenix Contact SAC", "Balluff BCC"],
      sources: [
        { type: "OEM", name: "Turck", url: "https://www.turck.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Automation24", url: "https://www.automation24.com/", region: "Europe, North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" }
      ]
    },
    {
      id: "balluff-bcc",
      name: "BCC M12 Connection Cable",
      brand: "Balluff",
      sku: "BCC",
      category: "Cables & Connectivity",
      family: "Sensor and actuator cables",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "M12 connection cable family for sensor and actuator wiring, automation cells, and replacement field cables.",
      applications: ["sensor wiring", "automation cells", "field devices"],
      specs: ["M12", "straight and angled", "PUR/PVC options", "A-coded options"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 80,
      cost: 68,
      balanced: 84,
      lead: "2-10 days",
      moq: "1 pc",
      alternatives: ["Murr M12 cordset", "Turck RK 4T", "Phoenix Contact SAC"],
      sources: [
        { type: "OEM", name: "Balluff", url: "https://www.balluff.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "TME", url: "https://www.tme.com/", region: "Europe, Middle East, Asia", action: "Buy or RFQ" },
        { type: "Distributor", name: "Automation24", url: "https://www.automation24.com/", region: "Europe, North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "fischer-faz-ii",
      name: "FAZ II Wedge Anchor",
      brand: "Fischer",
      sku: "FAZ II",
      category: "Fasteners & Hardware",
      family: "Concrete wedge anchors",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Mechanical wedge anchor family for concrete fastening, equipment baseplates, supports, and industrial installations.",
      applications: ["concrete anchoring", "equipment baseplates", "steel supports"],
      specs: ["wedge anchor", "ETA options", "carbon and stainless options", "concrete fastening"],
      certifications: ["ETA", "ICC-ES options"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 70,
      cost: 59,
      balanced: 78,
      lead: "1-3 weeks",
      moq: "box quantity",
      alternatives: ["Hilti HST3", "Rawlplug R-HPTII", "Powers wedge anchor"],
      sources: [
        { type: "OEM", name: "Fischer", url: "https://www.fischer-international.com/", region: "Global", action: "Product data" },
        { type: "Marketplace", name: "IndustryStock", url: "https://www.industrystock.com/", region: "Europe, Global", action: "Find suppliers" },
        { type: "Marketplace", name: "IndiaMART", url: "https://www.indiamart.com/", region: "Asia, Middle East", action: "Find suppliers" }
      ]
    },
    {
      id: "bossard-shcs",
      name: "Socket Head Cap Screw",
      brand: "Bossard",
      sku: "SHCS",
      category: "Fasteners & Hardware",
      family: "Industrial socket screws",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Industrial socket head cap screw family for machinery, maintenance, tooling, and assembly procurement.",
      applications: ["machine assembly", "tooling", "maintenance"],
      specs: ["socket head", "metric and inch options", "alloy steel", "stainless options"],
      certifications: ["ISO", "DIN"],
      datasheet: false,
      verified: true,
      lifecycle: "Active",
      speed: 84,
      cost: 78,
      balanced: 86,
      lead: "1-7 days",
      moq: "box quantity",
      alternatives: ["Unbrako SHCS", "Holo-Krome SHCS", "Fabory SHCS"],
      sources: [
        { type: "OEM", name: "Bossard", url: "https://www.bossard.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "MSC", url: "https://www.mscdirect.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Marketplace", name: "MISUMI", url: "https://www.misumi-ec.com/", region: "Global", action: "Buy or configure" }
      ]
    },
    {
      id: "keysight-u1282a",
      name: "U1282A Handheld Digital Multimeter",
      brand: "Keysight",
      sku: "U1282A",
      category: "Tools & MRO",
      family: "Industrial handheld multimeters",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Handheld digital multimeter for maintenance, commissioning, troubleshooting, and industrial electrical service.",
      applications: ["electrical maintenance", "commissioning", "troubleshooting"],
      specs: ["true RMS", "handheld", "industrial meter", "temperature options"],
      certifications: ["CE", "UL"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 76,
      cost: 62,
      balanced: 81,
      lead: "1-3 weeks",
      moq: "1 pc",
      alternatives: ["Fluke 87V", "Hioki DT4282", "Amprobe HD160C"],
      sources: [
        { type: "OEM", name: "Keysight", url: "https://www.keysight.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Mouser", url: "https://www.mouser.com/", region: "Global", action: "Buy or RFQ" },
        { type: "Distributor", name: "Newark", url: "https://www.newark.com/", region: "North America", action: "Buy or RFQ" }
      ]
    },
    {
      id: "3m-dp420",
      name: "Scotch-Weld DP420 Epoxy Adhesive",
      brand: "3M",
      sku: "DP420",
      category: "Tools & MRO",
      family: "Structural epoxy adhesives",
      regions: ["Europe", "Middle East", "Asia", "North America"],
      description: "Two-part structural epoxy adhesive used for maintenance bonding, fixture repair, panels, and industrial assemblies.",
      applications: ["maintenance bonding", "fixture repair", "industrial assemblies"],
      specs: ["two-part epoxy", "black or off-white options", "high strength", "cartridge system"],
      certifications: ["RoHS"],
      datasheet: true,
      verified: true,
      lifecycle: "Active",
      speed: 80,
      cost: 66,
      balanced: 84,
      lead: "2-10 days",
      moq: "1 cartridge",
      alternatives: ["Loctite EA 9460", "SikaPower epoxy", "Permabond epoxy adhesive"],
      sources: [
        { type: "OEM", name: "3M", url: "https://www.3m.com/", region: "Global", action: "Product data" },
        { type: "Distributor", name: "Grainger", url: "https://www.grainger.com/", region: "North America", action: "Buy or RFQ" },
        { type: "Distributor", name: "RS", url: "https://www.rs-online.com/", region: "Global", action: "Buy or RFQ" }
      ]
    }
  ]
};
